"""add event progress fields

Revision ID: 0342783fa665
Revises: 25126f6777bc
Create Date: 2026-07-22 22:09:57.898463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0342783fa665'
down_revision: Union[str, Sequence[str], None] = '25126f6777bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column(
        "events",
        sa.Column(
            "total_photos",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "processed_photos",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "events",
        sa.Column(
            "failed_photos",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    # Remove the defaults for future inserts.
    # SQLAlchemy's default=0 in your model will now handle new rows.
    op.alter_column("events", "total_photos", server_default=None)
    op.alter_column("events", "processed_photos", server_default=None)
    op.alter_column("events", "failed_photos", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'failed_photos')
    op.drop_column('events', 'processed_photos')
    op.drop_column('events', 'total_photos')
    # ### end Alembic commands ###
