"""sync face embeddings

Revision ID: dfd725420d36
Revises: de8d5f54ad42
Create Date: 2026-07-24 19:21:04.489897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfd725420d36'
down_revision: Union[str, Sequence[str], None] = 'de8d5f54ad42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.drop_table("face_embeddings")

    op.create_table(
        "face_embeddings",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "photo_id",
            sa.Integer(),
            sa.ForeignKey("photos.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("face_index", sa.Integer(), nullable=False),
        sa.Column("embedding", postgresql.ARRAY(sa.Float()), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )

    op.create_index("ix_face_embeddings_id", "face_embeddings", ["id"])
    op.create_index(
        "ix_face_embeddings_photo_id",
        "face_embeddings",
        ["photo_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.add_column('face_embeddings', sa.Column('bbox_y1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('face_embeddings', sa.Column('bbox_x1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('face_embeddings', sa.Column('bbox_x2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('face_embeddings', sa.Column('bbox_y2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_face_embeddings_photo_id'), table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_id'), table_name='face_embeddings')
    op.alter_column('face_embeddings', 'embedding',
               existing_type=postgresql.ARRAY(sa.Float()),
               type_=postgresql.BYTEA(),
               existing_nullable=False)
    op.drop_column('face_embeddings', 'created_at')
    op.drop_column('face_embeddings', 'height')
    op.drop_column('face_embeddings', 'width')
    op.drop_column('face_embeddings', 'y')
    op.drop_column('face_embeddings', 'x')
    # ### end Alembic commands ###
